version: "3.8"

services:

  content-service:
    build: ./content-service
    ports:
      - "3001:3001"

  streaming-service:
    build: ./streaming-service
    ports:
      - "3002:3002"

  user-service:
    build: ./user-service
    ports:
      - "3003:3003"

  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - content-service
      - streaming-service
      - user-service

  frontend:
  build: ./ott-frontend
  ports:
    - "3004:80"
  depends_on:
    - api-gateway
